[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
build_type = release

lib_deps =
    symlink://../..

build_unflags =
    -std=gnu++11
    -std=c++11

build_flags =
    -std=gnu++17
    -finput-charset=UTF-8
    -fexec-charset=UTF-8

build_src_flags =
    -fno-exceptions
    -fno-rtti

monitor_speed = 115200
